spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:test
    username: sa


logging:
  level:
    org.hibernate:
      SQL: DEBUG